theme: jekyll-theme-minimal
title: HPC Workshop Oct 15, 2024
description:  Van Andel institute High Performance Computing

# Navigation
# List links that should appear in the site sidebar here
navigation:
  - text: Documentation
    internal: true
    url: ./docs